In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')


In [3]:
# Load DataSet

df = pd.read_csv('D:\Python\datasets\Traffic Accident Severity Predictor Dataset.csv')
df.head(5)

Weather   Road_Type Time_of_Day  Traffic_Density  Speed_Limit  \
0   Rainy   City Road     Morning              1.0        100.0   
1   Clear  Rural Road       Night              NaN        120.0   
2   Rainy     Highway     Evening              1.0         60.0   
3   Clear   City Road   Afternoon              2.0         60.0   
4   Rainy     Highway     Morning              1.0        195.0   

   Number_of_Vehicles  Driver_Alcohol Accident_Severity      Road_Condition  \
0                 5.0             0.0               NaN                 Wet   
1                 3.0             0.0          Moderate                 Wet   
2                 4.0             0.0               Low                 Icy   
3                 3.0             0.0               Low  Under Construction   
4                11.0             0.0               Low                 Dry   

  Vehicle_Type  Driver_Age  Driver_Experience Road_Light_Condition  Accident  
0          Car        51.0               48.0     Artificial Light         0  
1        Truck        49.0               43.0     Artificial Light         0  
2          Car        54.0               52.0     Artificial Light         0  
3          Bus        34.0               31.0             Daylight         0  
4          Car        62.0               55.0     Artificial Light         1

In [4]:


# Handle missing values in target (Accident_Severity has some empties)
df = df.dropna(subset=['Accident_Severity'])

# Identify categorical and numerical columns
cat_cols = ['Weather', 'Road_Type', 'Time_of_Day', 'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition']
num_cols = ['Traffic_Density', 'Speed_Limit', 'Number_of_Vehicles', 'Driver_Alcohol', 'Driver_Age', 'Driver_Experience']

# Label encode categorical features
le_dict = {}
for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    le_dict[col] = le

# Features and target
X = df[cat_cols + num_cols]
y = df['Accident_Severity']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [8]:
# Scale numerical features
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

# Random Forest with GridSearchCV
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}
rf = RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(rf, param_grid, cv=5, scoring='accuracy', n_jobs=-1,)
grid_search.fit(X_train, y_train)

# Best model
best_rf = grid_search.best_estimator_
print("Best parameters:", grid_search.best_params_)


Best parameters: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}


In [6]:
# Predictions
y_pred = best_rf.predict(X_test)
y_pred_proba = best_rf.predict_proba(X_test)

# Metrics
print("Accuracy:", best_rf.score(X_test, y_test))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Feature importance
importances = best_rf.feature_importances_
feature_imp = pd.DataFrame({'feature': X.columns, 'importance': importances}).sort_values('importance', ascending=False)
print("\nTop Features:\n", feature_imp.head())


Accuracy: 0.594188376753507

Classification Report:
               precision    recall  f1-score   support

        High       0.00      0.00      0.00       401
         Low       0.59      1.00      0.75      2373
    Moderate       0.00      0.00      0.00      1218

    accuracy                           0.59      3992
   macro avg       0.20      0.33      0.25      3992
weighted avg       0.35      0.59      0.44      3992


Confusion Matrix:
 [[   0  401    0]
 [   0 2372    1]
 [   0 1218    0]]

Top Features:
                feature  importance
11   Driver_Experience    0.183487
10          Driver_Age    0.170247
7          Speed_Limit    0.112624
8   Number_of_Vehicles    0.100942
0              Weather    0.069726
